name: ipmonitoring
services:
  ipmonitoring:
    image: docker.io/library/ipmonitoring
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    # ports: # This is for reference. Add this port config to your gluetun container.
    #   - 1237:1237